<#
    Launches the Minespace instance directly, without a third-party launcher.
    Assembles the classpath from versions/ + libraries/ the same way the official
    launcher does, then starts Forge with the pack folder as the game directory.

    Generated by tools\install-pack.ps1 - edit that script, not this file.
#>
[CmdletBinding()]
param(
    [int]$MinMemoryMB = 2048,
    [int]$MaxMemoryMB = 6144,
    [string]$Username = 'Minespace',
    [switch]$Server
)
$ErrorActionPreference = 'Stop'
$Pack = $PSScriptRoot
$Java = Join-Path $Pack 'runtime\jdk8\bin\java.exe'
$ForgeId = '1.12.2-forge-14.23.5.2859'
$ForgeJson = Join-Path $Pack "versions\$ForgeId\$ForgeId.json"
$Natives = Join-Path $Pack "versions\$ForgeId\natives"

if (-not (Test-Path $Java)) { throw "Java 8 missing at $Java - run tools\install-pack.ps1 first" }
if (-not (Test-Path $ForgeJson)) { throw "Forge not installed ($ForgeJson) - run tools\install-pack.ps1 first" }

$forge = Get-Content -Raw $ForgeJson | ConvertFrom-Json
$base = Get-Content -Raw (Join-Path $Pack "versions\$($forge.inheritsFrom)\$($forge.inheritsFrom).json") | ConvertFrom-Json

# Libraries: the base version's list, then Forge's on top. Later entries win, so
# Forge's own library versions take precedence over vanilla ones.
$classpath = New-Object System.Collections.Generic.List[string]
foreach ($set in @($base.libraries, $forge.libraries)) {
    foreach ($lib in $set) {
        if ($lib.downloads.artifact.path) {
            $p = Join-Path $Pack ("libraries\" + ($lib.downloads.artifact.path -replace '/', '\'))
            if (Test-Path $p) { [void]$classpath.Add($p) }
        }
    }
}
$clientJar = Join-Path $Pack "versions\$($forge.inheritsFrom)\$($forge.inheritsFrom).jar"
[void]$classpath.Add($clientJar)
# Forge itself is not a versions/<id>/<id>.jar: the installer resolves it as a normal
# maven library, so it is already covered by the loop above. Only add an explicit entry
# if some future installer layout does put a jar next to the version json.
$versionJar = Join-Path $Pack "versions\$ForgeId\$ForgeId.jar"
if (Test-Path $versionJar) { [void]$classpath.Add($versionJar) }

$mainClass = if ($forge.mainClass) { $forge.mainClass } else { $base.mainClass }

$argsList = New-Object System.Collections.Generic.List[string]
[void]$argsList.Add("-Xmx${MaxMemoryMB}M")
[void]$argsList.Add("-Xms${MinMemoryMB}M")
[void]$argsList.Add("-Djava.library.path=$Natives")
[void]$argsList.Add('-Dfml.ignoreInvalidMinecraftCertificates=true')
[void]$argsList.Add('-Dfml.ignorePatchDiscrepancies=true')
if ($Server) {
    [void]$argsList.Add('-cp'); [void]$argsList.Add(($classpath -join ';'))
    [void]$argsList.Add($mainClass)
    [void]$argsList.Add('nogui')
} else {
    [void]$argsList.Add('-cp'); [void]$argsList.Add(($classpath -join ';'))
    [void]$argsList.Add($mainClass)
    [void]$argsList.Add('--username'); [void]$argsList.Add($Username)
    [void]$argsList.Add('--version'); [void]$argsList.Add($ForgeId)
    [void]$argsList.Add('--gameDir'); [void]$argsList.Add($Pack)
    [void]$argsList.Add('--assetsDir'); [void]$argsList.Add((Join-Path $Pack 'assets'))
    [void]$argsList.Add('--assetIndex'); [void]$argsList.Add($base.assetIndex.id)
    [void]$argsList.Add('--uuid'); [void]$argsList.Add('00000000000000000000000000000000')
    [void]$argsList.Add('--accessToken'); [void]$argsList.Add('0')
    [void]$argsList.Add('--userType'); [void]$argsList.Add('legacy')
    # Forge 1.12.2 is applied by launchwrapper through FML's tweaker. Without this the
    # launcher falls back to VanillaTweaker and crashes on the missing Minecraft class.
    [void]$argsList.Add('--tweakClass'); [void]$argsList.Add('net.minecraftforge.fml.common.launcher.FMLTweaker')
}

Write-Host "Launching $ForgeId (${MaxMemoryMB}M max heap)"
Push-Location $Pack
try { & $Java @argsList } finally { Pop-Location }
